### ISSUE TITLE
License Violation

### ISSUE THREAD

**Issue by mhambre** [remotevase/ImagicalMail#2]
GNU GPL 3 states that the product cannot be redistributed if modified

**Comment by remotevase** [comment]
This is a complete rewrite of the version for 0.10. That version was 1 simple php file. At first, I considered using only that file, until I read GNU GPL 3. Then I realized that the only way to do this plugin and post it on IM forums was to do an entire rewrite. Now I have multiple PHP files as opposed to one single file.

**Comment by 0-Eclipse-0** [comment]
https://github.com/Tschrock/PM-ServerMail
